// Generated by: python3 make_practice.py --sheet practice/system_of_eq_01.sheet.json
// The point of this is to incorporate in a single file the modular
// imports that I eventually will bundle in a package. Right now I
// don't want to bother with all that. So this file should work the
// way I want it to without any local package installs.

//#import "worksheet-headers.typ": first-page-header
//#import "question-env.typ": question, parts, choices

#set page(
  paper: "presentation-16-9",
  margin: 0.75in
)

#set text(
  font: "New Computer Modern",
  // font: "Linux Libertine O",
  size: 25pt,
)

#set par(
  justify: false,
  leading: 0.65em,
)

// Question Environment definitions
// Usage: #question(points: which is optional)[body of question]
//        #parts[] An inner environment for parts of a question
//        #choices(arrangement: stacked, linear, grid)[] for 
//          multiple choice questions

#let answer-blank(width) = box(
  width: width,
  inset: 0pt,
  stroke: (bottom: 0.7pt),
)

// Question counter
#let qnum = counter("question")

// Question environment
#let question(points: none, 
  space-below: 2em, 
  answer-line: none,
  renum: none,
  body
) = {
  if renum != none {
    qnum.update(renum - 1)
  }
  qnum.step()

  block(
    below: space-below,
    breakable: false,
  )[
    #grid(
      columns: (auto, 1fr, auto),
      column-gutter: 0.5em,

      [
        #context qnum.display("1.")
        #if answer-line != none [
          #answer-blank(answer-line)
        ]
     ],

      [
        #body
     ],

      [
        #if points != none [
          (#points pts)
       ]
     ],
    )
  ]
}

// Parts environment
#let parts(..items) = {
  stack(
    dir: ttb,
    spacing: 0.75em,

    ..items.pos().enumerate().map(((i, item)) => [
      #numbering("(a)", i + 1)
      #h(0.5em)
      #item
    ])
  )
}

// choices environment for multiple choice questions
#let choices(arrangement: "vertical", ..items) = {
  let labeled = items.pos().enumerate().map(((i, item)) => (
    numbering("A.", i + 1),
    item,
  ))

  if arrangement == "vertical" {
    // Original behavior: one choice per line
    stack(
      dir: ttb,
      spacing: 3em,
      ..labeled.map(((label, item)) => [
        #grid(
          columns: (auto, 1fr),
          [#label #h(0.25em)],
          [#item]
        )
      ])
    )

  } else if arrangement == "linear" {
    [
      #parbreak()
      // All choices on one line
      #labeled.map(((label, item)) => [
        #label #h(0.25em) #item #h(1fr)
      ]).join()
    ]

  } else if arrangement == "grid" {
    // chunk into pairs, padding with empty if odd
    let pairs = range(0, labeled.len(), step: 2).map(i => {
      let a = labeled.at(i)
      let b = if i + 1 < labeled.len() { labeled.at(i + 1) } else { none }
      (a, b)
    })

    stack(
      dir: ttb,
      spacing: 3em,
      ..pairs.map(((a, b)) =>
        grid(
          columns: (1fr, 1fr),
          gutter: 12pt,
          [
            #grid(
              columns: (auto, 1fr),
              [#a.at(0) #h(0.25em)],
              [#a.at(1)],
            ) 
          ],
          if b != none [
            #grid(
              columns: (auto, 1fr),
              [#b.at(0) #h(0.25em)],
              [#b.at(1)],
            ) 
          ] else [],
        )
      )
    )
  } else {
    panic("choices: unknown arrangement '" + arrangement + "'. Use vertical, linear, or grid.")
  }
}



#let first-page-header(class-name, worksheet-title, version: "1") = [
  #v(-0.25in)
  #grid(
    columns: (1fr, auto),
    column-gutter: 0pt,
    row-gutter: 1.4em,

    [#class-name],
    align(right)[Name #answer-blank(7cm)],

    [#set text(size: 15pt, weight: "bold"); #worksheet-title],
    align(right)[Date #answer-blank(3.5cm) Ver: #version],
  )
  #v(3em)
]

// ==================================================
// DOCUMENT VARIABLES
// ==================================================

#let class-name = "Algebra 1"
#let worksheet-title = "System of Equations 1"
#let version = "1"


#let slide(n, prob, answer: none) = {
  align(left)[#text(size: 30pt, weight: "bold")[Problem #n]]
  v(1.5em)
  align(center)[
    #text(size: 34pt)[#prob]
    #if answer != none [
      #v(0.8em)
      #text(fill: red, size: 34pt)[#answer]
    ]
  ]
}

#let type-slide(lbl, title, look, move) = align(horizon)[
  #text(size: 24pt, fill: luma(90))[#lbl]
  #v(-0.3em)
  #text(size: 40pt, weight: "bold")[#title]
  #v(0.6em)
  #text(size: 24pt)[*Look for:* #look]
  #v(0.2em)
  #text(size: 24pt)[*The move:* #move]
]

#let group-slide(heading, items) = align(horizon)[
  #text(size: 40pt, weight: "bold")[#heading]
  #v(0.5em)
  #for it in items [
    #text(size: 20pt)[*#it.at(0): #it.at(1)* #h(0.4em) _Look for:_ #it.at(2) #h(0.4em) _The move:_ #it.at(3)]
    #v(0.35em)
  ]
]

#align(center + horizon)[
  #text(size: 44pt, weight: "bold")[#worksheet-title]
  #v(0.4em)
  #text(size: 28pt)[Version 1]
  #v(0.2em)
  #text(size: 24pt)[Solve each system of equations.]
]
#pagebreak()
#type-slide([Type 1], [Back-Substitute], [One equation has a single variable, and another has just two.], [Solve the one-variable equation, substitute into the two-variable one, then into the last.])
#pagebreak()
#slide(1, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    2x, -, 3y, +, z, =, -39;
    4x, , , +, z, =, -18;
    x, , , , , =, -3))$])
#pagebreak()
#slide(1, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    2x, -, 3y, +, z, =, -39;
    4x, , , +, z, =, -18;
    x, , , , , =, -3))$], answer: [$(-3, 9, -6)$])
#pagebreak()
#slide(2, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    4x, +, 3y, -, 3z, =, -8;
    , , 5y, +, z, =, 16;
    , , 2y, , , =, 4))$])
#pagebreak()
#slide(2, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    4x, +, 3y, -, 3z, =, -8;
    , , 5y, +, z, =, 16;
    , , 2y, , , =, 4))$], answer: [$(1, 2, 6)$])
#pagebreak()
#type-slide([Type 4], [Eliminate], [Every variable in every equation, and some coefficients are 1 or −1.], [Pick the variable with a coefficient of 1 or −1 and eliminate it from two pairs of equations.])
#pagebreak()
#slide(3, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    2x, -, y, +, 4z, =, -17;
    5x, +, 4y, -, 5z, =, 48;
    3x, -, y, -, 7z, =, 17))$])
#pagebreak()
#slide(3, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    2x, -, y, +, 4z, =, -17;
    5x, +, 4y, -, 5z, =, 48;
    3x, -, y, -, 7z, =, 17))$], answer: [$(1, 7, -3)$])
#pagebreak()
#slide(4, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    x, -, 7y, +, 7z, =, -22;
    7x, +, 6y, +, 6z, =, 4;
    2x, +, y, +, 5z, =, 10))$])
#pagebreak()
#slide(4, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    x, -, 7y, +, 7z, =, -22;
    7x, +, 6y, +, 6z, =, 4;
    2x, +, y, +, 5z, =, 10))$], answer: [$(-8, 6, 4)$])
#pagebreak()
#slide(5, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    x, -, 6y, +, z, =, -46;
    4x, -, 3y, -, 3z, =, -51;
    x, +, y, -, 7z, =, -30))$])
#pagebreak()
#slide(5, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    x, -, 6y, +, z, =, -46;
    4x, -, 3y, -, 3z, =, -51;
    x, +, y, -, 7z, =, -30))$], answer: [$(-3, 8, 5)$])
#pagebreak()
#slide(6, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    4x, +, y, +, 4z, =, 13;
    x, -, 3y, +, z, =, 26;
    3x, +, 4y, -, 3z, =, -37))$])
#pagebreak()
#slide(6, [$display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    4x, +, y, +, 4z, =, 13;
    x, -, 3y, +, z, =, 26;
    3x, +, 4y, -, 3z, =, -37))$], answer: [$(1, -7, 4)$])
