// Generated by: python3 make_practice.py --sheet practice/system_of_eq_01.sheet.json
// The point of this is to incorporate in a single file the modular
// imports that I eventually will bundle in a package. Right now I
// don't want to bother with all that. So this file should work the
// way I want it to without any local package installs.

//#import "worksheet-headers.typ": first-page-header
//#import "question-env.typ": question, parts, choices

#set page(
  paper: "us-letter",
  margin: 0.75in
)

#set text(
  font: "New Computer Modern",
  // font: "Linux Libertine O",
  size: 12pt,
)

#set par(
  justify: false,
  leading: 0.65em,
)

// Question Environment definitions
// Usage: #question(points: which is optional)[body of question]
//        #parts[] An inner environment for parts of a question
//        #choices(arrangement: stacked, linear, grid)[] for 
//          multiple choice questions

#let answer-blank(width) = box(
  width: width,
  inset: 0pt,
  stroke: (bottom: 0.7pt),
)

// Question counter
#let qnum = counter("question")

// Question environment
#let question(points: none, 
  space-below: 2em, 
  answer-line: none,
  renum: none,
  body
) = {
  if renum != none {
    qnum.update(renum - 1)
  }
  qnum.step()

  block(
    // height: space-below,
    breakable: false,
  )[
    #grid(
      columns: (auto, 1fr, auto),
      column-gutter: 0.5em,

      [
        #context qnum.display("1.")
        #if answer-line != none [
          #answer-blank(answer-line)
        ]
     ],

      [
        #body
     ],

      [
        #if points != none [
          (#points pts)
       ]
     ],
    )
    #v(space-below)
  ]
}

// Parts environment
#let parts(..items) = {
  stack(
    dir: ttb,
    spacing: 0.75em,

    ..items.pos().enumerate().map(((i, item)) => [
      #numbering("(a)", i + 1)
      #h(0.5em)
      #item
    ])
  )
}

// choices environment for multiple choice questions
#let choices(arrangement: "vertical", ..items) = {
  let labeled = items.pos().enumerate().map(((i, item)) => (
    numbering("A.", i + 1),
    item,
  ))

  if arrangement == "vertical" {
    // Original behavior: one choice per line
    stack(
      dir: ttb,
      spacing: 3em,
      ..labeled.map(((label, item)) => [
        #grid(
          columns: (auto, 1fr),
          [#label #h(0.25em)],
          [#item]
        )
      ])
    )

  } else if arrangement == "linear" {
    [
      #parbreak()
      // All choices on one line
      #labeled.map(((label, item)) => [
        #label #h(0.25em) #item #h(1fr)
      ]).join()
    ]

  } else if arrangement == "grid" {
    // chunk into pairs, padding with empty if odd
    let pairs = range(0, labeled.len(), step: 2).map(i => {
      let a = labeled.at(i)
      let b = if i + 1 < labeled.len() { labeled.at(i + 1) } else { none }
      (a, b)
    })

    stack(
      dir: ttb,
      spacing: 3em,
      ..pairs.map(((a, b)) =>
        grid(
          columns: (1fr, 1fr),
          gutter: 12pt,
          [
            #grid(
              columns: (auto, 1fr),
              [#a.at(0) #h(0.25em)],
              [#a.at(1)],
            ) 
          ],
          if b != none [
            #grid(
              columns: (auto, 1fr),
              [#b.at(0) #h(0.25em)],
              [#b.at(1)],
            ) 
          ] else [],
        )
      )
    )
  } else {
    panic("choices: unknown arrangement '" + arrangement + "'. Use vertical, linear, or grid.")
  }
}

#let instructions-block(txt, above: auto, below: auto) = block(
  sticky: true,
  above: above,
  below: below,
  text(style: "italic", weight: "regular")[#txt],
)

#let section-head(
  txt,
  instructions: none,
) = block(
  sticky: true,
  above: 1.1em,
  below: 1em,
  {
    text(weight: "bold", size: 14pt)[#txt]
    if instructions != none {
      v(0.9em, weak: true)
      instructions-block(instructions)
      v(0.5em, weak: true)
    }
  },
)

#let first-page-header(class-name, worksheet-title, version: "1") = [
  #v(-0.25in)
  #grid(
    columns: (1fr, auto),
    column-gutter: 0pt,
    row-gutter: 1.4em,

    [#class-name],
    align(right)[Name #answer-blank(7cm)],

    [#set text(size: 15pt, weight: "bold"); #worksheet-title],
    align(right)[Date #answer-blank(3.5cm) Ver: #version],
  )
  #v(3em)
]

// ==================================================
// DOCUMENT VARIABLES
// ==================================================

#let class-name = "Algebra 1"
#let worksheet-title = "System of Equations 1"
#let version = "1"

#first-page-header(class-name, worksheet-title, version: version)
#v(-2.2em)
#instructions-block([Solve each system of equations.])

#section-head[Type 1: Back-Substitute]
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 2.5in)[
    $display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    2x, -, 3y, +, z, =, -39;
    4x, , , +, z, =, -18;
    x, , , , , =, -3))$
  ],
  question(space-below: 2.5in)[
    $display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    4x, +, 3y, -, 3z, =, -8;
    , , 5y, +, z, =, 16;
    , , 2y, , , =, 4))$
  ],
)

#section-head[Type 4: Eliminate]
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 2.5in)[
    $display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    2x, -, y, +, 4z, =, -17;
    5x, +, 4y, -, 5z, =, 48;
    3x, -, y, -, 7z, =, 17))$
  ],
  question(space-below: 2.5in)[
    $display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    x, -, 7y, +, 7z, =, -22;
    7x, +, 6y, +, 6z, =, 4;
    2x, +, y, +, 5z, =, 10))$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 2.5in)[
    $display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    x, -, 6y, +, z, =, -46;
    4x, -, 3y, -, 3z, =, -51;
    x, +, y, -, 7z, =, -30))$
  ],
  question(space-below: 2.5in)[
    $display(mat(delim: #("{", none), align: #right, column-gap: #0.2em,
    4x, +, y, +, 4z, =, 13;
    x, -, 3y, +, z, =, 26;
    3x, +, 4y, -, 3z, =, -37))$
  ],
)
