# Literal Equations by Type

Algebra 1 materials for solving literal equations (formulas) for a given
variable. The equations are sorted into eleven **types** by the first move
each one needs, plus two **special cases**. There are two parts:

1. **The lesson set:** 50 equations in sequence, with a worksheet, an answer
   key, a slide deck, a worked-examples guide, and a reference sheet that
   solves every equation for every variable.
2. **A practice generator:** new problems of whatever types you choose, as
   many versions as you like. It writes a worksheet, an answer key, and a
   slide deck for each version. You can run it from the command line or from
   a terminal app with vim keys.

Every answer, and every line of every worked example, is checked
numerically with sympy before anything is written.

## Quick start

```sh
# Rebuild the lesson set
python3 gen_sequence.py && for f in *.typ; do typst compile "$f"; done

# Practice sets from the command line
python3 make_practice.py --mix 3:6 8:4 A:2 --versions 3 --seed 12

# Practice sets interactively (press ? inside for keys)
python3 practice_tui.py
```

The practice files go into `practice/`. See [MANUAL.md](MANUAL.md) for the
details.

## The types

| Key | Type | Lesson problems |
|---|---|---|
| 1 | One Step | 1–8 |
| 2 | Add or Subtract, Then Divide | 9–12 |
| 3 | Clear One Denominator | 13–18 |
| 4 | Distribute First | 19–24 |
| 5 | Clear a Denominator, Then Distribute | 25–27 |
| 6 | Clear Two Denominators | 28–29 |
| 7 | Factor Out, Then Divide | 30–31 |
| 8 | Gather, Factor Out, Divide | 32–35 |
| 9 | Distribute, Gather, Factor Out, Divide | 36–38 |
| 10 | Clear Single-Term Denominators, Then Solve | 39–41 |
| 11 | Clear a Multi-Term Denominator | 42–45 |
| A | Special Case: Watch the Sign | 46–47 |
| B | Special Case: Finish with a Square Root | 48–50 |

## Files

| File | What it is |
|---|---|
| `literal_common.py` | Shared code: the type definitions, Typst-to-sympy parsing and numeric checks, and the Typst preambles |
| `gen_sequence.py` | Builds the lesson set (`lesson_1-4_literal_seq_*`) |
| `make_practice.py` | Practice generator: templates, the formula pool, the solver and answer formatter, Typst output, and the command line |
| `practice_tui.py` | Terminal app over `make_practice.py` |
| `tests/` | `test_tui_keys.py` (no terminal needed) and `screen_test.py` (draws the real screen; needs `pyte`) |
| `lesson_1-4_literal_seq_*` | The lesson set: worksheet, key, slides, guide, all-solutions reference, JSON bank |
| `practice/` | Default output folder for practice sets |
| `EXTENDING.md` | A brief for an LLM (or a person) turning this into a general worksheet builder |

## Requirements

- Python 3.10+ with **sympy** (tested with 1.13).
- **Typst** 0.15 to compile PDFs. Without it, the `.typ` files are still written.
- The worksheet and slide styles come from `../../mixed_review/mixed_review_v1.typ`
  and `mixed_review_slides.typ`. They are read at run time, so keep that
  folder where it is or update the paths in `literal_common.py`.
- Optional: `pyte`, only for `tests/screen_test.py`.

## Reproducibility

The same settings and seed always give the same problems. Each practice file
begins with the exact command that recreates it, for example
`// Generated by: python3 make_practice.py --mix 3:6 8:4 A:2 --versions 2 --seed 12`.
The matching `.json` file stores that command too, and `practice_tui.py`
can reopen it.
