// Generated by: python3 make_practice.py --mix 1:6 2:6 3:6 4:6 5:6 --versions 1 --seed 10003 --title 'Literal Equations Steps 1-5' --out '~/Documents/alg1/unit_1/lesson_1-4/' --name literal_eq_steps_01-05
// The point of this is to incorporate in a single file the modular
// imports that I eventually will bundle in a package. Right now I
// don't want to bother with all that. So this file should work the
// way I want it to without any local package installs.

//#import "worksheet-headers.typ": first-page-header
//#import "question-env.typ": question, parts, choices

#set page(
  paper: "us-letter",
  margin: 0.75in
)

#set text(
  font: "New Computer Modern",
  // font: "Linux Libertine O",
  size: 12pt,
)

#set par(
  justify: false,
  leading: 0.65em,
)

// Question Environment definitions
// Usage: #question(points: which is optional)[body of question]
//        #parts[] An inner environment for parts of a question
//        #choices(arrangement: stacked, linear, grid)[] for 
//          multiple choice questions

#let answer-blank(width) = box(
  width: width,
  inset: 0pt,
  stroke: (bottom: 0.7pt),
)

// Question counter
#let qnum = counter("question")

// Question environment
#let question(points: none, 
  space-below: 2em, 
  answer-line: none,
  renum: none,
  body
) = {
  if renum != none {
    qnum.update(renum - 1)
  }
  qnum.step()

  block(
    // height: space-below,
    breakable: false,
  )[
    #grid(
      columns: (auto, 1fr, auto),
      column-gutter: 0.5em,

      [
        #context qnum.display("1.")
        #if answer-line != none [
          #answer-blank(answer-line)
        ]
     ],

      [
        #body
     ],

      [
        #if points != none [
          (#points pts)
       ]
     ],
    )
    #v(space-below)
  ]
}

// Parts environment
#let parts(..items) = {
  stack(
    dir: ttb,
    spacing: 0.75em,

    ..items.pos().enumerate().map(((i, item)) => [
      #numbering("(a)", i + 1)
      #h(0.5em)
      #item
    ])
  )
}

// choices environment for multiple choice questions
#let choices(arrangement: "vertical", ..items) = {
  let labeled = items.pos().enumerate().map(((i, item)) => (
    numbering("A.", i + 1),
    item,
  ))

  if arrangement == "vertical" {
    // Original behavior: one choice per line
    stack(
      dir: ttb,
      spacing: 3em,
      ..labeled.map(((label, item)) => [
        #grid(
          columns: (auto, 1fr),
          [#label #h(0.25em)],
          [#item]
        )
      ])
    )

  } else if arrangement == "linear" {
    [
      #parbreak()
      // All choices on one line
      #labeled.map(((label, item)) => [
        #label #h(0.25em) #item #h(1fr)
      ]).join()
    ]

  } else if arrangement == "grid" {
    // chunk into pairs, padding with empty if odd
    let pairs = range(0, labeled.len(), step: 2).map(i => {
      let a = labeled.at(i)
      let b = if i + 1 < labeled.len() { labeled.at(i + 1) } else { none }
      (a, b)
    })

    stack(
      dir: ttb,
      spacing: 3em,
      ..pairs.map(((a, b)) =>
        grid(
          columns: (1fr, 1fr),
          gutter: 12pt,
          [
            #grid(
              columns: (auto, 1fr),
              [#a.at(0) #h(0.25em)],
              [#a.at(1)],
            ) 
          ],
          if b != none [
            #grid(
              columns: (auto, 1fr),
              [#b.at(0) #h(0.25em)],
              [#b.at(1)],
            ) 
          ] else [],
        )
      )
    )
  } else {
    panic("choices: unknown arrangement '" + arrangement + "'. Use vertical, linear, or grid.")
  }
}

#let instructions-block(txt, above: auto, below: auto) = block(
  sticky: true,
  above: above,
  below: below,
  text(style: "italic", weight: "regular")[#txt],
)

#let section-head(
  txt,
  instructions: none,
) = block(
  sticky: true,
  above: 1.1em,
  below: 1em,
  {
    text(weight: "bold", size: 14pt)[#txt]
    if instructions != none {
      v(0.9em, weak: true)
      instructions-block(instructions)
      v(0.5em, weak: true)
    }
  },
)

#let first-page-header(class-name, worksheet-title, version: "1") = [
  #v(-0.25in)
  #grid(
    columns: (1fr, auto),
    column-gutter: 0pt,
    row-gutter: 1.4em,

    [#class-name],
    align(right)[Name #answer-blank(7cm)],

    [#set text(size: 15pt, weight: "bold"); #worksheet-title],
    align(right)[Date #answer-blank(3.5cm) Ver: #version],
  )
  #v(3em)
]

// ==================================================
// DOCUMENT VARIABLES
// ==================================================

#let class-name = "Algebra 1"
#let worksheet-title = "Literal Equations Steps 1-5"
#let version = "1"

#first-page-header(class-name, worksheet-title, version: version)
#v(-2.2em)
#instructions-block([Solve each equation for the indicated variable.])

#section-head()[Type 1: One Step] 
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(R = s - 6)$; #h(0.3em) $s$
  ],
  question(space-below: 3em)[
    $display(d = r t)$; #h(0.3em) $r$
  ],
)

#grid(
  question(space-below: 3em)[
    $display(7 c d = V)$; #h(0.3em) $d$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(n = a + z)$; #h(0.3em) $z$
  ],
  question(space-below: 3em)[
    $display(K = p - 7)$; #h(0.3em) $p$
  ],
)

#section-head(instructions: "These are my instructions.")[Type 2: Add or Subtract, Then Divide]
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(b = q c - m)$; #h(0.3em) $c$
  ],
  question(space-below: 3em)[
    $display(v = c + 5 a)$; #h(0.3em) $a$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(w = c n + x d)$; #h(0.3em) $d$
  ],
  question(space-below: 3em)[
    $display(H = t p + n q)$; #h(0.3em) $p$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(v^2 = u^2 + 2 a s)$; #h(0.3em) $a$
  ],
  question(space-below: 3em)[
    $display(7 = v z + p)$; #h(0.3em) $z$
  ],
)

#section-head([Type 3: Clear One Denominator])
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(G = 1/2 p)$; #h(0.3em) $p$
  ],
  question(space-below: 3em)[
    $display(t/4 + p = u)$; #h(0.3em) $t$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(D = y/k - 2)$; #h(0.3em) $y$
  ],
  question(space-below: 3em)[
    $display(D = m/V)$; #h(0.3em) $V$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(c = (s - 11)/d)$; #h(0.3em) $s$
  ],
  question(space-below: 13em)[
    $display(c = (4 s)/k)$; #h(0.3em) $k$
  ],
)

#section-head([Type 4: Distribute First])
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(y - y_1 = m(x - x_1))$; #h(0.3em) $x$
  ],
  question(space-below: 3em)[
    $display(w(h - 3 v) = 7 c)$; #h(0.3em) $v$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(A = P(1 + r t))$; #h(0.3em) $r$
  ],
  question(space-below: 3em)[
    $display(q = m c(T_f - T_i))$; #h(0.3em) $T_f$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(5(4 n + z) = 4(z - n))$; #h(0.3em) $z$
  ],
  question(space-below: 3em)[
    $display(S = 180(n - 2))$; #h(0.3em) $n$
  ],
)

#section-head([Type 5: Clear a Denominator, Then Distribute])
#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(a = (w(r + 5))/y)$; #h(0.3em) $r$
  ],
  question(space-below: 3em)[
    $display(K = (p(v - 7))/w)$; #h(0.3em) $v$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display((9(m + r))/t = D)$; #h(0.3em) $m$
  ],
  question(space-below: 3em)[
    $display(1/2 r(w + 13) = c)$; #h(0.3em) $w$
  ],
)

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  question(space-below: 3em)[
    $display(a = 4/5 (h + r))$; #h(0.3em) $h$
  ],
  question(space-below: 3em)[
    $display(F = (2(k - u))/z)$; #h(0.3em) $k$
  ],
)

