"""Typst preambles (read from templates/ at import) and text escaping."""
import re
from . import ROOT

MARK = "// ==================================================\n// DOCUMENT VARIABLES"
head = (ROOT / "templates/mixed_review_v1.typ").read_text()
head = head[:head.index(MARK)]
slhead = (ROOT / "templates/mixed_review_slides.typ").read_text()
slhead = slhead[:slhead.index(MARK)]
# The worksheet preamble: the teacher's refined template, minus its own
# "Generated by" line and everything from DOCUMENT VARIABLES on.
sheet_head = (ROOT / "templates/refined_template.typ").read_text()
sheet_head = "".join(l for l in sheet_head[:sheet_head.index(MARK)].splitlines(keepends=True)
                     if not l.startswith("// Generated by:"))

def tstr(text):
    """A Typst string literal."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'

def vars_(title, version="1", class_name="Algebra 1"):
    return f'''{MARK}
// ==================================================

#let class-name = {tstr(class_name)}
#let worksheet-title = {tstr(title)}
#let version = {tstr(version)}

'''

def esc(text):
    """Make plain text safe inside a Typst [content block]."""
    return re.sub(r"([\\#$\[\]*_@<>`~])", r"\\\1", text)
