"""Typst for a sheet: the worksheet, the answer key, and the slide deck.

The worksheet follows templates/refined_template.typ: the header, the
sheet's instructions block, then for each section a section-head (when it
has a title) and one #grid per row of problems (see sheet.rows).
"""
from . import banks
from .sheet import problem, rows
from .typst import sheet_head, slhead, vars_, esc

def _content(text):
    return f"[{esc(text)}]"

def _question(it, v, key):
    b = banks.get(it["bank"])
    p = problem(it, v)
    # The answer floats in the work space, so the key breaks pages where the sheet does.
    a = (f"\n    #place(right, dy: 0.5em)[#text(fill: red)[{b.answer_typst(p)}] #h(0.4em)]" if key else "")
    return f"  question(space-below: {it['space']})[\n    {b.typst(p)}{a}\n  ],\n"

def worksheet(sheet, v=0, key=False):
    """Typst for version v (0-based) of the sheet, or its answer key."""
    title = sheet["title"] + (" — Answer Key" if key else "")
    s = (f"// Generated by: {sheet['command']}\n" if sheet.get("command") else "")
    s += sheet_head + vars_(title, str(v + 1), sheet["class_name"])
    s += "#first-page-header(class-name, worksheet-title, version: version)\n#v(-2.2em)\n"
    if sheet["instructions"]:
        s += f"#instructions-block({_content(sheet['instructions'])})\n"
    for sec in sheet["sections"]:
        if not sec["items"]:
            continue
        s += "\n" if s.endswith(")\n") else ""
        if sec["title"]:
            ins = f"(instructions: {_content(sec['instructions'])})" if sec["instructions"] else ""
            s += f"#section-head{ins}{_content(sec['title'])}\n"
        elif sec["instructions"]:
            s += f"#instructions-block({_content(sec['instructions'])})\n"
        for row in rows(sec["items"]):
            cols = "  columns: (1fr, 1fr),\n  column-gutter: 1em,\n" if row[0]["width"] == "half" else ""
            s += "#grid(\n" + cols + "".join(_question(it, v, key) for it in row) + ")\n\n"
    return s.rstrip("\n") + "\n"

def _section_slide(sec):
    """The title slide for a section: a type's hints when the section is all one
    type, every type's hints when it mixes types of one bank, else just its title."""
    bs = [banks.get(it["bank"]) for it in sec["items"]]
    if len({b.FAMILY for b in bs}) == 1:
        hints = list(dict.fromkeys(b.hint(b.type_of(it["entry"])) for b, it in zip(bs, sec["items"])))
        if None not in hints:
            if len(hints) == 1:
                lbl, ttl, look, move = hints[0]
                b, t = bs[0], bs[0].type_of(sec["items"][0]["entry"])
                name = ttl if sec["title"] == b.heading(t) else esc(sec["title"])
                return f"#pagebreak()\n#type-slide([{lbl}], [{name}], [{look}], [{move}])\n"
            items = ", ".join("([{}], [{}], [{}], [{}])".format(*h) for h in hints)
            return f"#pagebreak()\n#group-slide({_content(sec['title'])}, ({items}))\n"
    return f"#pagebreak()\n#group-slide({_content(sec['title'])}, ())\n"

def slides(sheet, v=0):
    """Typst for the slide deck of version v (0-based)."""
    titled = [sec for sec in sheet["sections"] if sec["title"] and sec["items"]]
    most = max([len({(banks.get(it["bank"]).FAMILY, banks.get(it["bank"]).type_of(it["entry"]))
                     for it in sec["items"]}) for sec in titled] or [0])
    s = (f"// Generated by: {sheet['command']}\n" if sheet.get("command") else "")
    s += slhead + vars_(sheet["title"], str(v + 1), sheet["class_name"]) + f"""
#let slide(n, prob, answer: none) = {{
  align(left)[#text(size: 30pt, weight: "bold")[Problem #n]]
  v(1.5em)
  align(center)[
    #text(size: 34pt)[#prob]
    #if answer != none [
      #v(0.8em)
      #text(fill: red, size: 34pt)[#answer]
    ]
  ]
}}

#let type-slide(lbl, title, look, move) = align(horizon)[
  #text(size: 24pt, fill: luma(90))[#lbl]
  #v(-0.3em)
  #text(size: 40pt, weight: "bold")[#title]
  #v(0.6em)
  #text(size: 24pt)[*Look for:* #look]
  #v(0.2em)
  #text(size: 24pt)[*The move:* #move]
]

#let group-slide(heading, items) = align(horizon)[
  #text(size: 40pt, weight: "bold")[#heading]
  #v(0.5em)
  #for it in items [
    #text(size: {20 if most <= 4 else 17}pt)[*#it.at(0): #it.at(1)* #h(0.4em) _Look for:_ #it.at(2) #h(0.4em) _The move:_ #it.at(3)]
    #v(0.35em)
  ]
]

#align(center + horizon)[
  #text(size: 44pt, weight: "bold")[#worksheet-title]
  #v(0.4em)
  #text(size: 28pt)[Version {v + 1}]
  #v(0.2em)
  #text(size: 24pt){_content(sheet["instructions"])}
]
"""
    n = 0
    for sec in sheet["sections"]:
        if not sec["items"]:
            continue
        if sec["title"]:
            s += _section_slide(sec)
        for it in sec["items"]:
            n += 1
            b, p = banks.get(it["bank"]), problem(it, v)
            pr = b.typst(p, gap="0.5em")
            s += f"#pagebreak()\n#slide({n}, [{pr}])\n"
            s += f"#pagebreak()\n#slide({n}, [{pr}], answer: [{b.answer_typst(p)}])\n"
    return s
